[package]
name = "axns"
version = "0.1.0"
edition = "2024"

[dependencies]
spin = { version = "0.10", default-features = false, features = ["lazy"] }

extern-trait = { version = "0.1.1", optional = true }

[dev-dependencies]
parking_lot = { version = "0.12.3", features = ["arc_lock"] }

[features]
thread-local = ["dep:extern-trait"]
